on: push
name: CombineBluetoothKit DevelopCI
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: |
          xcodebuild clean test -project CombineBluetoothKit.xcodeproj -scheme CombineBluetoothKit -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}